---
- name: Update RHEL servers (web, db, nfs)
  hosts: webservers, db, nfs
  become: yes
  tasks:
    - name: Ensure wireshark is installed
      yum:
        name: wireshark
        state: latest

- name: Update Ubuntu servers (LB)
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Ensure wireshark is installed
      apt:
        name: wireshark
        state: latest
