- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is installed
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is installed
      apt:
        name: wireshark
        state: latest
